### ISSUE TITLE
WISDM error - Step 2 Spatial Data Preparation - Can't pickle local object / serialize

### ISSUE THREAD

**Issue by aciocco** [ApexRMS/wisdm#18]
Attempting to run a mock model, failure on step 2 error code below.  May be due to larger rasters at relatively high resolution 1km requiring lots of spatial tiling.

2 - Spatial Data Preparation => Total time: 00:01:40
[Failure] The external program failed.
Program name was: C:\Users\aciocco\AppData\Local\SyncroSim3\Conda\envs\wisdm-1\wisdm-conda-s3\Python.exe
Arguments were: "C:\Users\aciocco\AppData\Local\SyncroSim3\Packages\wisdm\2.0.0\2-spatial-data-preparation.py"
Exit code was: 1
More information:
2024-08-20 11:18:40,301 - distributed.protocol.pickle - ERROR - Failed to serialize <ToPickle: HighLevelGraph with 1 layers.
<dask.highlevelgraph.HighLevelGraph object at 0x20c394c1cd0>
0. 2251785495872
>.
Traceback (most recent call last):
  File "C:\Users\aciocco\AppData\Local\SyncroSim3\Conda\envs\wisdm-1\wisdm-conda-s3\Lib\site-packages\distributed\protocol\pickle.py", line 63, in dumps
    result = pickle.dumps(x, **dump_kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
AttributeError: Can't pickle local object 'map_blocks.<locals>._wrapper'
During handling of the above exception, another exception occurred:
Traceback (most recent call last):
  File "C:\Users\aciocco\AppData\Local\SyncroSim3\Conda\envs\wisdm-1\wisdm-conda-s3\Lib\site-packages\distributed\protocol\pickle.py", line 68, in dumps
    pickler.dump(x)

**Comment by katieb1** [comment]
This should now be fixed in this commit: https://github.com/ApexRMS/wisdm/commit/99edfc7e12c7f6e92a6733bb6ae8e38516fe97ca#diff-2981603e4c88a7d16ccba69511c414d27c5552e681d1061ba8ace8b997d06f0a
