### ISSUE TITLE
[BUG]

### ISSUE THREAD

**Issue by lfraser1** [ApexRMS/wisdm#19]
**Describe the bug**
Step 2- Spatial Data Preparation fails. 

**To Reproduce**
I have a zip with the rasters for the template, covariates, and points as well as the library I produced, but it's too big to attach. If you need it, please let me know who to send it to.  

**Expected behavior**
I expect spatial data preparation to occur, in which the covariates and template data are used.

**Relevant log output**
SyncroSim Version: 3.0.2.0
Operating System: Microsoft Windows NT 6.2.9200.0

Packages:
core -> 3.0.2
wisdm -> 2.0.1

Parent Scenario is: [1] Brassica tournifortii
Result scenario is: [6] Brassica tournifortii ([1] @ 16-Sep-2024 3:01 PM)

--------------------------------------------
STARTING SIMULATION: 9/16/2024 : 3:01:35 PM
--------------------------------------------

Conda installation: C:\Users\lfraser\AppData\Local\SyncroSim3\Conda
Conda environment: C:\Users\lfraser\AppData\Local\SyncroSim3\Conda\envs\wisdm-1\wisdm-conda-s3

1 - Prepare Multiprocessing => Total time: 00:04:45

Conda installation: C:\Users\lfraser\AppData\Local\SyncroSim3\Conda
Conda environment: C:\Users\lfraser\AppData\Local\SyncroSim3\Conda\envs\wisdm-1\wisdm-conda-s3

2 - Spatial Data Preparation => Total time: 00:00:27
[Failure] The external program failed.
Program name was: C:\Users\lfraser\AppData\Local\SyncroSim3\Conda\envs\wisdm-1\wisdm-conda-s3\Python.exe
Arguments were: "C:\Users\lfraser\AppData\Local\SyncroSim3\Packages\wisdm\2.0.1\2-spatial-data-preparation.py"
Exit code was: 1
More information:
Traceback (most recent call last):
  File "C:\Users\lfraser\AppData\Local\SyncroSim3\Packages\wisdm\2.0.1\2-spatial-data-preparation.py", line 407, in <module>
    prep_spatial_data()
  File "C:\Users\lfraser\AppData\Local\SyncroSim3\Packages\wisdm\2.0.1\2-spatial-data-preparation.py", line 214, in prep_spatial_data
    covariateRaster = rioxarray.open_rasterio(covariatePath, chunks=True)
                      ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\lfraser\AppData\Local\SyncroSim3\Conda\envs\wisdm-1\wisdm-conda-s3\Lib\site-packages\rioxarray\_io.py", line 1128, in open_rasterio
    riods = manager.acquire()
            ^^^^^^^^^^^^^^^^^
  File "C:\Users\lfraser\AppData\Local\SyncroSim3\Conda\envs\wisdm-1\wisdm-conda-s3\Lib\site-packages\rioxarray\_io.py", line 263, in acquire
    return self._local.thread_manager.file_handle
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\lfraser\AppData\Local\SyncroSim3\Conda\envs\wisdm-1\wisdm-conda-s3\Lib\site-packages\rioxarray\_io.py", line 219, in file_handle
    self._file_handle = self._opener(*self._args, mode=self._mode, **self._kwargs)
                        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\lfraser\AppData\Local\SyncroSim3\Conda\envs\wisdm-1\wisdm-conda-s3\Lib\site-packages\rasterio\env.py", line 451, in wrapper
    return f(*args, **kwds)
           ^^^^^^^^^^^^^^^^
  File "C:\Users\lfraser\AppData\Local\SyncroSim3\Conda\envs\wisdm-1\wisdm-conda-s3\Lib\site-packages\rasterio\__init__.py", line 216, in open
    raise TypeError("invalid path or file: {0!r}".format(fp))
TypeError: invalid path or file: nan

--------------------------------------------
SIMULATION COMPLETE: 9/16/2024 : 3:06:48 PM
--------------------------------------------
Total simulation time: 00:05:13

**Software versions:**
 - SyncroSim: 3.0.2
 - WISDM  2.0.1

**Comment by lfraser1** [comment]
Okay, it seems I deleted the raster path name, but not the entire variable itself for a variable I was removing. So SyncroSim was still looking for the raster path to my "clay" variable. Once I deleted the entire line under the covariate datasheet for that variable the issue resolved.

**Comment by katieb1** [comment]
That's interesting that SyncroSim wouldn't flag the cell as being required once you removed the raster file path. That seems like it could be a bug in the validation to me.
