### ISSUE TITLE
rasterio failure during spatial data prep 

### ISSUE THREAD

**Issue by LeonardoFrid** [ApexRMS/wisdm#5]
am getting the following error running wisdm 1.0.7 with conda.  It sounds like [rasterio](https://github.com/rasterio/rasterio) has a more recent version ([1.3.6](https://github.com/rasterio/rasterio/releases/tag/1.3.6)) and the conda environment for wisdm needs to get updated.

[Failure] The external program failed.
Program name was: C:\Users\LeonardoFrid\SyncroSim\Conda\envs\wisdm\wisdm-py-conda\Python.exe
Arguments were: "C:\Users\LeonardoFrid\SyncroSim\Packages\wisdm\2-spatial-data-preparation.py"
Exit code was: 1
More information:
Traceback (most recent call last):
  File "C:\Users\LeonardoFrid\SyncroSim\Packages\wisdm\2-spatial-data-preparation.py", line 14, in <module>
    import pysyncrosim as ps     
  File "C:\Users\LeonardoFrid\SyncroSim\Conda\envs\wisdm\wisdm-py-conda\lib\site-packages\pysyncrosim\__init__.py", line 5, in <module>
    from pysyncrosim.raster import Raster
  File "C:\Users\LeonardoFrid\SyncroSim\Conda\envs\wisdm\wisdm-py-conda\lib\site-packages\pysyncrosim\raster.py", line 2, in <module>
    import rasterio
  File "C:\Users\LeonardoFrid\SyncroSim\Conda\envs\wisdm\wisdm-py-conda\lib\site-packages\rasterio\__init__.py", line 28, in <module>
    from rasterio._version import gdal_version, get_geos_version, get_proj_version
ImportError: DLL load failed while importing _version: The specified procedure could not be found.

**Comment by LeonardoFrid** [comment]
After updating to wisdm 1.0.8 I am no longer getting this error.
